# Generated by Django 4.2 on 2023-05-31 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeURL',
            fields=[
                ('id', models.BigAutoField(help_text='YouTube url ID', primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='YouTube url')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='YouTube Title', max_length=50)),
                ('length', models.IntegerField(help_text='YouTube Length')),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('end_time', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
        migrations.CreateModel(
            name='STTResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('end_time', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('conf', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
    ]
