# Generated by Django 3.2.1 on 2023-07-27 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeURL',
            fields=[
                ('id', models.BigAutoField(help_text='YouTube url ID', primary_key=True, serialize=False)),
                ('url', models.URLField(help_text='YouTube url')),
                ('status', models.CharField(default='created', help_text='Status', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='YouTube Title', max_length=50)),
                ('length', models.BigIntegerField(help_text='YouTube Length')),
                ('video_size', models.JSONField()),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeCaption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('end_time', models.BigIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
        migrations.CreateModel(
            name='STTResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField(blank=True, null=True)),
                ('end_time', models.BigIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.BigIntegerField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('conf', models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True)),
                ('bbox', models.JSONField(blank=True, null=True)),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
    ]
