# Generated by Django 3.2.1 on 2023-06-15 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubeurl',
            name='status',
            field=models.CharField(default=False, help_text='Status', max_length=10),
        ),
    ]
