# Generated by Django 3.2.1 on 2023-07-27 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='STTKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField()),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
        migrations.CreateModel(
            name='OCRKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField()),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
        migrations.CreateModel(
            name='CaptionKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.JSONField()),
                ('url_id', models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl')),
            ],
        ),
    ]
