# Generated by Django 4.2.1 on 2023-05-31 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ai_model", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ocrresult",
            name="url_id",
            field=models.ForeignKey(
                db_column="url_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_model.youtubeurl",
            ),
        ),
        migrations.AlterField(
            model_name="sttresult",
            name="url_id",
            field=models.ForeignKey(
                db_column="url_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_model.youtubeurl",
            ),
        ),
        migrations.AlterField(
            model_name="youtubecaption",
            name="url_id",
            field=models.ForeignKey(
                db_column="url_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_model.youtubeurl",
            ),
        ),
        migrations.AlterField(
            model_name="youtubeinfo",
            name="url_id",
            field=models.ForeignKey(
                db_column="url_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="ai_model.youtubeurl",
            ),
        ),
    ]
