# Generated by Django 3.2.1 on 2023-07-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0002_youtubeurl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubeurl',
            name='status',
            field=models.CharField(default='created', help_text='Status', max_length=10),
        ),
    ]
