# Generated by Django 4.2 on 2023-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0002_remove_youtubeurl_length_remove_youtubeurl_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sttresult',
            old_name='time',
            new_name='end_time',
        ),
        migrations.RenameField(
            model_name='youtubecaption',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='sttresult',
            name='start_time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='youtubecaption',
            name='start_time',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True),
        ),
    ]
