# Generated by Django 3.2.1 on 2023-07-27 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0003_alter_youtubeurl_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrresult',
            name='time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sttresult',
            name='end_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sttresult',
            name='start_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubecaption',
            name='end_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubecaption',
            name='start_time',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubeinfo',
            name='length',
            field=models.BigIntegerField(help_text='YouTube Length'),
        ),
    ]
