# Generated by Django 4.2 on 2023-05-28 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ai_model', '0003_rename_time_sttresult_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocrresult',
            name='url_id',
            field=models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl'),
        ),
        migrations.AlterField(
            model_name='sttresult',
            name='url_id',
            field=models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl'),
        ),
        migrations.AlterField(
            model_name='youtubecaption',
            name='url_id',
            field=models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl'),
        ),
        migrations.AlterField(
            model_name='youtubeinfo',
            name='url_id',
            field=models.ForeignKey(db_column='url_id', on_delete=django.db.models.deletion.CASCADE, to='ai_model.youtubeurl'),
        ),
    ]
